apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
      app: redis
      role: primary
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
        app: redis
        role: primary
    spec:
      containers:
        - name: redis
          image: "redis:{{- .Values.version }}"
          {{- if and (eq (.Values.authentication).require true) (gt (len (.Values.authentication).password) 0) }}
          command: [ "redis-server", "--requirepass", "{{ .Values.authentication.password }}" ]
          {{ end }}
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    instance: {{ .Release.Name }}
    app: redis
    role: primary
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379