{{- if (.Values.replication).enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-replica
spec:
  replicas: {{ (.Values.replication).replicas }}
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
      app: redis
      role: replica
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: "redis:{{- .Values.version }}"
          {{- if and (eq ((.Values.authentication).require) true) (gt (len ((.Values.authentication).password)) 0) }}
          command: ["redis-server", "--requirepass", "{{ .Values.authentication.password }}", "--slaveof", "{{ .Release.Name }}-redis", "6379"]
          {{ else }}
          command: ["redis-server", "--slaveof", "{{ .Release.Name }}-redis", "6379"]
          {{ end -}}
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-replica
spec:
  selector:
    instance: {{ .Release.Name }}
    app: redis
    role: replica
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end }}
